// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookstore.Data;

namespace OnlineBookstore.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e73",
                            ConcurrencyStamp = "eedf6e88-27ae-414f-a9c7-5f4fae390eba",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e74",
                            ConcurrencyStamp = "0a26153b-c160-4c8a-a9b6-89ace82a943d",
                            Name = "editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e75",
                            ConcurrencyStamp = "dac19500-dabc-453f-8046-cb96ca6bb21d",
                            Name = "guest",
                            NormalizedName = "GUEST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "b4280b6a-0613-4cbd-a9e6-f1701e926e73",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8554266-b401-4519-9aeb-a9283053fc58",
                            Email = "admin@onlinebookstore.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ONLINEBOOKSTORE.COM",
                            NormalizedUserName = "ADMIN@ONLINEBOOKSTORE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEH06y7nsx97ELG+erHxCoRis07KzdxYR8PWeNqRWSdgMIsxwy62dwd3J1Qnthh8saA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin@onlinebookstore.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "b4280b6a-0613-4cbd-a9e6-f1701e926e73",
                            RoleId = "b4280b6a-0613-4cbd-a9e6-f1701e926e73"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("OnlineBookstore.Data.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("Popularity")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Agatha Christie",
                            Popularity = false,
                            ShortDescription = "Dame Agatha Mary Clarissa Christie, Lady Mallowan, DBE (née Miller; 15 September 1890 – 12 January 1976) was an English writer known for her 66 detective novels and 14 short story collections, particularly those revolving around fictional detectives Hercule Poirot and Miss Marple. She also wrote the world's longest-running play The Mousetrap and six romances under the pen name Mary Westmacott. In 1971, she was appointed a Dame Commander of the Order of the British Empire (DBE) for her contribution to literature"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stephen King",
                            Popularity = true,
                            ShortDescription = "Stephen Edwin King (born September 21, 1947) is an American author of horror, supernatural fiction, suspense, and fantasy novels. His books have sold more than 350 million copies, many of which have been adapted into feature films, miniseries, television series, and comic books. King has published 61 novels (including seven under the pen name Richard Bachman) and six non-fiction books. He has written approximately 200 short stories, most of which have been published in book collections."
                        },
                        new
                        {
                            Id = 3,
                            Name = "William Shakespeare",
                            Popularity = false,
                            ShortDescription = "William Shakespeare (bapt. 26 April 1564 – 23 April 1616) was an English poet, playwright, and actor, widely regarded as the greatest writer in the English language and the world's greatest dramatist. He is often called England's national poet and the \"Bard of Avon\" (or simply \"the Bard\"). His extant works, including collaborations, consist of some 39 plays, 154 sonnets, two long narrative poems, and a few other verses, some of uncertain authorship. His plays have been translated into every major living language and are performed more often than those of any other playwright"
                        },
                        new
                        {
                            Id = 4,
                            Name = "J. K. Rowling",
                            Popularity = false,
                            ShortDescription = "Joanne Rowling CH, OBE, HonFRSE, FRCPE, FRSL, (born 31 July 1965), better known by her pen name J. K. Rowling, is a British author, film producer, television producer, screenwriter, and philanthropist. She is best known for writing the Harry Potter fantasy series,which has won multiple awards and sold more than 500 million copies, becoming the best-selling book series in history. The books are the basis of a popular film series, over which Rowling had overall approval on the scripts and was a producer on the final films. She also writes crime fiction under the name Robert Galbraith."
                        },
                        new
                        {
                            Id = 5,
                            Name = "Leo Tolstoy",
                            Popularity = false,
                            ShortDescription = "Count Lev Nikolayevich Tolstoy (9 September [O.S. 28 August] 1828 – 20 November [O.S. 7 November] 1910), usually referred to in English as Leo Tolstoy, was a Russian writer who is regarded as one of the greatest authors of all time. He received multiple nominations for the Nobel Prize in Literature every year from 1902 to 1906, and nominations for Nobel Peace Prize in 1901, 1902 and 1910, and the fact that he never won is a major Nobel prize controversy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Paulo Coelho",
                            Popularity = false,
                            ShortDescription = "Paulo Coelho de Souza (born 24 August 1947) is a Brazilian lyricist and novelist, best known for his novel The Alchemist. In 2014, he uploaded his personal papers online to create a virtual Paulo Coelho Foundation"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jeffrey Archer",
                            Popularity = false,
                            ShortDescription = "Jeffrey Howard Archer (born 15 April 1940) is an English novelist, former politician, convicted perjurer, and peer of the realm. Before becoming an author,Archer was a Member of Parliament(1969–1974), but did not seek re - election after a financial scandal that left him almost bankrupt.He revived his fortunes as a best - selling novelist; his books have sold around 330 million copies worldwide"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ian Fleming",
                            Popularity = false,
                            ShortDescription = "Ian Lancaster Fleming (28 May 1908 – 12 August 1964) was an English author, journalist and naval intelligence officer who is best known for his James Bond series of spy novels. Fleming came from a wealthy family connected to the merchant bank Robert Fleming & Co., and his father was the Member of Parliament for Henley from 1910 until his death on the Western Front in 1917. Educated at Eton, Sandhurst and, briefly, the universities of Munich and Geneva, Fleming moved through several jobs before he started writing."
                        },
                        new
                        {
                            Id = 9,
                            Name = "Nicholas Sparks",
                            Popularity = false,
                            ShortDescription = "Nicholas Charles Sparks (born December 31, 1965) is an American romance novelist and screenwriter. He has published twenty novels and two non-fiction books. Several of his novels have become international bestsellers, and eleven of his romantic-drama novels have been adapted to film all with multimillion-dollar box office grosses.His novels feature stories of tragic love with happy endings."
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dan Brown",
                            Popularity = false,
                            ShortDescription = "Daniel Gerhard Brown (born June 22, 1964) is an American author best known for his thriller novels, including the Robert Langdon novels Angels & Demons (2000), The Da Vinci Code (2003), The Lost Symbol (2009), Inferno (2013) and Origin (2017). His novels are treasure hunts that usually take place over a period of 24 hours.[2] They feature recurring themes of cryptography, art, and conspiracy theories. His books have been translated into 57 languages and, as of 2012, have sold over 200 million copies. Three of them, Angels & Demons, The Da Vinci Code, and Inferno, have been adapted into films."
                        });
                });

            modelBuilder.Entity("OnlineBookstore.Data.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(350)")
                        .HasMaxLength(350);

                    b.Property<string>("BookType")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(350)")
                        .HasMaxLength(350);

                    b.Property<int>("Copies")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Edition")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PublisherID")
                        .HasColumnType("int");

                    b.Property<string>("PublisherName")
                        .HasColumnType("nvarchar(350)")
                        .HasMaxLength(350);

                    b.Property<string>("Shipping")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("SoldItems")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(350)")
                        .HasMaxLength(350);

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<DateTime>("YearOfIssue")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PublisherID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorID = 1,
                            AuthorName = "Agatha Cristie",
                            BookType = "Paperback",
                            CategoryID = 1,
                            CategoryName = "Fiction",
                            Copies = 100,
                            Country = "UK",
                            Description = "Book seed 1 Description",
                            Dimensions = "12x12x20",
                            Edition = 1,
                            Genre = "Fiction",
                            Language = "English",
                            NumberOfPages = 586,
                            PhotoURL = "AgathaCristie_MurderOnTheOrientExpress.jpg",
                            Price = 9.9900000000000002,
                            PublisherID = 1,
                            PublisherName = "William Morrow Paperbacks",
                            Shipping = "Free",
                            SoldItems = 20,
                            Title = "Murder On The Orient Express",
                            Weight = 0.48999999999999999,
                            YearOfIssue = new DateTime(2020, 2, 29, 23, 29, 25, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AuthorID = 2,
                            AuthorName = "Stephen King",
                            BookType = "Paperback",
                            CategoryID = 6,
                            CategoryName = "Fantasy",
                            Copies = 50,
                            Country = "",
                            Description = "Now a major motion picture starring Matthew McConaughey and Idris Elba. An impressive work of mythic magnitude that may turn out to be Stephen King's greatest literary achievement (The Atlanta Journal-Constitution), The Gunslinger is the first volume in the epic Dark Tower Series. A #1 national bestseller, The Gunslinger introduces readers to one of Stephen King's most powerful creations, Roland of Gilead: The Last Gunslinger. He is a haunting figure, a loner on a spellbinding journey into good and evil. In his desolate world, which mirrors our own in frightening ways, Roland tracks The Man in Black, encounters an enticing woman named Alice, and begins a friendship with the boy from New York named Jake. Inspired in part by the Robert Browning narrative poem,Childe Roland to the Dark Tower Came, The Gunslinger is a compelling whirlpool of a story that draws one irretrievable to its center ( Milwaukee Sentinel ). It is brilliant and fresh...and will leave you panting for more ( Booklist ).",
                            Dimensions = "Not known",
                            Edition = 1,
                            Genre = "Fantasy",
                            Language = "English",
                            NumberOfPages = 586,
                            PhotoURL = "StephenKing_The_Dark_Tower.jpg",
                            Price = 11.48,
                            PublisherID = 2,
                            PublisherName = "Scholastic",
                            Shipping = "Free",
                            SoldItems = 19,
                            Title = "The Dark Tower I: The Gunslinger",
                            Weight = 0.59999999999999998,
                            YearOfIssue = new DateTime(2017, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AuthorID = 2,
                            AuthorName = "Stephen King",
                            BookType = "Paperback",
                            CategoryID = 9,
                            CategoryName = "Horror",
                            Copies = 20,
                            Country = "USA",
                            Description = "Once upon a time, in the haunted city of Derry (site of the classics \"It\" and \"Insomnia),\" four boys stood together and did a brave thing. Certainly a good thing, perhaps even a great thing. Something that changed them in ways they could never begin to understand. Twenty - five years later, the boys are now men with separate lives and separate troubles. But the ties endure. Each hunting season the foursome reunite in the woods of Maine. This year, a stranger stumbles into their camp, disoriented, mumbling something about lights in the sky. His incoherent ravings prove to be dis - turbingly prescient.Before long, these men will be plunged into a horrifying struggle with a creature from another world. Their only chance of survival is locked in their shared past-- and in the Dreamcatcher.",
                            Dimensions = "6.51 x 9.56 x 2.01 inches",
                            Edition = 1,
                            Genre = "Horror",
                            Language = "English",
                            NumberOfPages = 624,
                            PhotoURL = "StephenKing_Dreamcatcher.jpg",
                            Price = 13.98,
                            PublisherID = 7,
                            PublisherName = "Simon & Schuster",
                            Shipping = "Free",
                            SoldItems = 3,
                            Title = "Dreamcatcher",
                            Weight = 2.2200000000000002,
                            YearOfIssue = new DateTime(2020, 2, 29, 23, 29, 25, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AuthorID = 2,
                            AuthorName = "Stephen King",
                            BookType = "Paperback",
                            CategoryID = 8,
                            CategoryName = "General",
                            Copies = 150,
                            Country = "USA",
                            Description = "Stephen King's international bestselling - and highly acclaimed - novel, also a hugely successful film starring Tom Hanks",
                            Dimensions = "5.12 x 7.80 x 1.22 inches",
                            Edition = 1,
                            Genre = "Drama",
                            Language = "English",
                            NumberOfPages = 480,
                            PhotoURL = "StephenKing-The-Green-Mile.jpg",
                            Price = 23.98,
                            PublisherID = 9,
                            PublisherName = "Houghton Mifflin Harcourt",
                            Shipping = "Free",
                            SoldItems = 4,
                            Title = "The Green Mile",
                            Weight = 0.48999999999999999,
                            YearOfIssue = new DateTime(2005, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AuthorID = 2,
                            AuthorName = "Stephen King",
                            BookType = "Paperback",
                            CategoryID = 9,
                            CategoryName = "Horror",
                            Copies = 200,
                            Country = "USA",
                            Description = "Old Ralph Roberts hasn't been sleeping well lately. Every night he wakes just a little bit earlier, and pretty soon, he thinks, he won't get any sleep at all. It wouldn't be so bad, except for the strange hallucinations he's been having. Or, at least, he hopes they are hallucinations--because here in Derry, one never can tell. Part of the \"Books That Take You Anywhere You Want To Go\" Summer Reading Promotion.",
                            Dimensions = "4.21 x 6.93 x 1.51 inches",
                            Edition = 1,
                            Genre = "Horror",
                            Language = "English",
                            NumberOfPages = 663,
                            PhotoURL = "StephenKing_Insomnia.jpg",
                            Price = 12.98,
                            PublisherID = 5,
                            PublisherName = "HarperCollins",
                            Shipping = "Free",
                            SoldItems = 5,
                            Title = "Insomnia",
                            Weight = 0.69999999999999996,
                            YearOfIssue = new DateTime(1995, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AuthorID = 2,
                            AuthorName = "Stephen King",
                            BookType = "Paperback",
                            CategoryID = 7,
                            CategoryName = "Thrillers",
                            Copies = 40,
                            Country = "USA",
                            Description = "Evil forces try to destroy a boy with psychic powers.",
                            Dimensions = "6.44 x 9.42 x 1.46 inches",
                            Edition = 1,
                            Genre = "Thriller",
                            Language = "English",
                            NumberOfPages = 450,
                            PhotoURL = "StephenKing_The-Shining.jpg",
                            Price = 33.479999999999997,
                            PublisherID = 5,
                            PublisherName = "HarperCollins",
                            Shipping = "Free",
                            SoldItems = 6,
                            Title = "The Shining",
                            Weight = 1.6799999999999999,
                            YearOfIssue = new DateTime(1990, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AuthorID = 2,
                            AuthorName = "Stephen King",
                            BookType = "Paperback",
                            CategoryID = 9,
                            CategoryName = "Horror",
                            Copies = 230,
                            Country = "USA",
                            Description = "Now repackaged with stunning new cover art, this #1 bestseller is a chilling story set in a lonely Nevada town where the evil embedded in the landscape is awesome--but so are the forces summoned to combat it. Reissue",
                            Dimensions = "4.22 x 6.86 x 1.52 inches",
                            Edition = 1,
                            Genre = "Horror",
                            Language = "English",
                            NumberOfPages = 547,
                            PhotoURL = "StephenKing_Desperation.jpg",
                            Price = 22.98,
                            PublisherID = 10,
                            PublisherName = "Pearson Education",
                            Shipping = "Free",
                            SoldItems = 7,
                            Title = "Desperation",
                            Weight = 0.48999999999999999,
                            YearOfIssue = new DateTime(2003, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AuthorID = 3,
                            AuthorName = "William Shakespeare",
                            BookType = "Paperback",
                            CategoryID = 5,
                            CategoryName = "Drama",
                            Copies = 65,
                            Country = "UK",
                            Description = "Shakespeare's tragedy about Othello the Moor is presented in this freshly edited text with full explanatory notes, scene-by-scene plot summaries, an Introduction to reading Shakespeare's language, and much more. Reissue.",
                            Dimensions = "4.10 x 6.70 x 1.00 inches",
                            Edition = 1,
                            Genre = "Drama",
                            Language = "English",
                            NumberOfPages = 368,
                            PhotoURL = "WilliamShakespeare_Othello.jpg",
                            Price = 5.9800000000000004,
                            PublisherID = 7,
                            PublisherName = "Simon & Schuster",
                            Shipping = "Free",
                            SoldItems = 18,
                            Title = "Othello",
                            Weight = 0.40000000000000002,
                            YearOfIssue = new DateTime(2003, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AuthorID = 4,
                            AuthorName = "J. K. Rowling",
                            BookType = "Paperback",
                            CategoryID = 1,
                            CategoryName = "Fiction",
                            Copies = 131,
                            Country = "UK",
                            Description = "The one that started the biggest publishing phenomenon of our time",
                            Dimensions = "4.45 x 7.01 x 0.87 inches",
                            Edition = 1,
                            Genre = "Fiction",
                            Language = "English",
                            NumberOfPages = 336,
                            PhotoURL = "Harry-Potter-and-the-Philosopher-s-Stone-Rowling-J-K.jpg",
                            Price = 9.9800000000000004,
                            PublisherID = 1,
                            PublisherName = "William Morrow Paperbacks",
                            Shipping = "Free",
                            SoldItems = 17,
                            Title = "Harry Potter and the Philosopher's Stone",
                            Weight = 0.34999999999999998,
                            YearOfIssue = new DateTime(2004, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AuthorID = 6,
                            AuthorName = "Paulo Coelho",
                            BookType = "Paperback",
                            CategoryID = 1,
                            CategoryName = "Fiction",
                            Copies = 222,
                            Country = "UK",
                            Description = "This international bestseller about the shepherd boy Santiago who learns how to live his dreams includes an inspiring afterword by the author.",
                            Dimensions = "5.36 x 8.02 x 0.56 inches",
                            Edition = 1,
                            Genre = "Fiction",
                            Language = "English",
                            NumberOfPages = 197,
                            PhotoURL = "PauloCoelho_The-Alchemist.jpg",
                            Price = 6.9800000000000004,
                            PublisherID = 1,
                            PublisherName = "William Morrow Paperbacks",
                            Shipping = "Free",
                            SoldItems = 16,
                            Title = "The Alchemist",
                            Weight = 0.48999999999999999,
                            YearOfIssue = new DateTime(2006, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AuthorID = 6,
                            AuthorName = "Paulo Coelho",
                            BookType = "Paperback",
                            CategoryID = 1,
                            CategoryName = "Fiction",
                            Copies = 34,
                            Country = "USA",
                            Description = "This gripping and daring novel by the author of the bestselling \"The Alchemist\" sensitively explores the sacred nature of sex and love. \"Sensual. . . for-adults - only fairytale.\"--\"Washington Post.\"",
                            Dimensions = "5.32 x 8.04 x 0.77 inches",
                            Edition = 1,
                            Genre = "Fiction",
                            Language = "English",
                            NumberOfPages = 320,
                            PhotoURL = "PauloCoelho_Eleven-Minutes.jpg",
                            Price = 12.48,
                            PublisherID = 5,
                            PublisherName = "HarperCollins",
                            Shipping = "Free",
                            SoldItems = 8,
                            Title = "Eleven Minutes",
                            Weight = 0.52000000000000002,
                            YearOfIssue = new DateTime(2005, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AuthorID = 7,
                            AuthorName = "Jeffrey Archer",
                            BookType = "Paperback",
                            CategoryID = 1,
                            CategoryName = "Fiction",
                            Copies = 87,
                            Country = "USA",
                            Description = "Jeffrey Archer's mesmerizing saga of the Clifton and Barrington families continues... 1945, London. The vote in the House of Lords as to who should inherit the Barrington family fortune has ended in a tie. The Lord Chancellor's deciding vote will cast a long shadow on the lives of Harry Clifton and Giles Barrington. Harry returns to America to promote his latest novel, while his beloved Emma goes in search of the little girl who was found abandoned in her father's office on the night he was killed. When the general election is called, Giles Barrington has to defend his seat in the House of Commons and is horrified to discover who the Conservatives select to stand against him. But it is Sebastian Clifton, Harry and Emma's son, who ultimately influences his uncle's fate. In 1957, Sebastian wins a scholarship to Cambridge, and a new generation of the Clifton family marches onto the page. But after Sebastian is expelled from school, he unwittingly becomes caught up in an international art fraud involving a Rodin statue that is worth far more than the sum it raises at auction. Does he become a millionaire? Does he go to Cambridge? Is his life in danger?",
                            Dimensions = "4.32 x 6.04 x 0.57 inches",
                            Edition = 1,
                            Genre = "Fiction",
                            Language = "English",
                            NumberOfPages = 423,
                            PhotoURL = "ArcherJeffrey-Best-Kept-Secret.jpg",
                            Price = 14.48,
                            PublisherID = 4,
                            PublisherName = "Hachette Livre",
                            Shipping = "Free",
                            SoldItems = 9,
                            Title = "Best Kept Secret (The Clifton Chronicles)",
                            Weight = 0.56999999999999995,
                            YearOfIssue = new DateTime(2014, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AuthorID = 8,
                            AuthorName = "Ian Fleming",
                            BookType = "Paperback",
                            CategoryID = 2,
                            CategoryName = "Action",
                            Copies = 122,
                            Country = "UK",
                            Description = "In the novel that introduced James Bond to the world, Ian Fleming's agent 007 is dispatched to a French casino in Royale-les-Eaux. His mission? Bankrupt a ruthless Russian agent who's been on a bad luck streak at the baccarat table. One of SMERSH's most deadly operatives, the man known only as ?Le Chiffre, ? has been a prime target of the British Secret Service for years. If Bond can wipe out his bankroll, Le Chiffre will likely be ?retired? by his paymasters in Moscow. But what if the cards won't cooperate? After a brutal night at the gaming tables, Bond soon finds himself dodging would-be assassins, fighting off brutal torturers, and going all-in to save the life of his beautiful female counterpart, Vesper Lynd. Taut, tense, and effortlessly stylish, Ian Fleming's inaugural James Bond adventure has all the hallmarks that made the series a touchstone for a generation of readers.",
                            Dimensions = "4.32 x 6.04 x 0.57 inches",
                            Edition = 1,
                            Genre = "Action",
                            Language = "English",
                            NumberOfPages = 486,
                            PhotoURL = "IanFlemming_Casino_Royale.jpg",
                            Price = 13.48,
                            PublisherID = 3,
                            PublisherName = "Penguin Random House",
                            Shipping = "Free",
                            SoldItems = 15,
                            Title = "Casino Royale",
                            Weight = 0.29999999999999999,
                            YearOfIssue = new DateTime(2012, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AuthorID = 8,
                            AuthorName = "Ian Fleming",
                            BookType = "Paperback",
                            CategoryID = 2,
                            CategoryName = "Action",
                            Copies = 10,
                            Country = "UK",
                            Description = "The lethal SMERSH organization in Russia has targeted Agent 007 for elimination. But when James Bond allows himself to be lured to Istanbul and walks willingly into a trap, a game of cross and double-cross ensues, with Bond as both the stakes and the prize.",
                            Dimensions = "5.12 x 7.72 x 0.53 inches",
                            Edition = 1,
                            Genre = "Action",
                            Language = "English",
                            NumberOfPages = 272,
                            PhotoURL = "IanFleming_From-Russia-with-Love.jpg",
                            Price = 6.4800000000000004,
                            PublisherID = 3,
                            PublisherName = "Penguin Random House",
                            Shipping = "Free",
                            SoldItems = 14,
                            Title = "From Russia with Love",
                            Weight = 0.41999999999999998,
                            YearOfIssue = new DateTime(2002, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AuthorID = 9,
                            AuthorName = "Nicholas Sparks",
                            BookType = "Paperback",
                            CategoryID = 1,
                            CategoryName = "Fiction",
                            Copies = 37,
                            Country = "UK",
                            Description = "No description is available.",
                            Dimensions = "4.10 x 6.70 x 1.00 inches",
                            Edition = 1,
                            Genre = "Romance",
                            Language = "English",
                            NumberOfPages = 463,
                            PhotoURL = "NicolasSparks_Every13Breath.jpg",
                            Price = 8.9800000000000004,
                            PublisherID = 4,
                            PublisherName = "Hachette Livre",
                            Shipping = "Free",
                            SoldItems = 13,
                            Title = "Every Breath",
                            Weight = 0.5,
                            YearOfIssue = new DateTime(2010, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AuthorID = 9,
                            AuthorName = "Nicholas Sparks",
                            BookType = "Paperback",
                            CategoryID = 1,
                            CategoryName = "Fiction",
                            Copies = 44,
                            Country = "UK",
                            Description = "#1 bestselling author Nicholas Sparks's new novel is at once a compelling family drama and a heartrending tale of young love.Seventeen year old Veronica \"Ronnie\" Miller's life was turned upside-down when her parents divorced and her father moved from New York City to Wilmington, North Carolina. Three years later, she remains angry and alientated from her parents, especially her father...until her mother decides it would be in everyone's best interest if she spent the summer in Wilmington with him. Ronnie's father, a former concert pianist and teacher, is living a quiet life in the beach town, immersed in creating a work of art that will become the centerpiece of a local church.The tale that unfolds is an unforgettable story of love on many levels--first love, love between parents and children -- that demonstrates, as only a Nicholas Sparks novel can, the many ways that love can break our hearts...and heal them.",
                            Dimensions = "4.10 x 6.70 x 1.00 inches",
                            Edition = 1,
                            Genre = "Romance",
                            Language = "English",
                            NumberOfPages = 463,
                            PhotoURL = "NicolasSparks_The-Last-Song.jpg",
                            Price = 8.9800000000000004,
                            PublisherID = 4,
                            PublisherName = "Hachette Livre",
                            Shipping = "Free",
                            SoldItems = 10,
                            Title = "The Last Song",
                            Weight = 0.5,
                            YearOfIssue = new DateTime(2010, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AuthorID = 10,
                            AuthorName = "Dan Brown",
                            BookType = "Paperback",
                            CategoryID = 7,
                            CategoryName = "Thrillers",
                            Copies = 111,
                            Country = "USA",
                            Description = "PREMIUM MASS MARKET EDITION #1 Worldwide Bestseller--More Than 80 Million Copies Sold As millions of readers around the globe have already discovered, The Da Vinci Code is a reading experience unlike any other.Simultaneously lightning - paced, intelligent,and intricately layered with remarkable research and detail, Dan Brown's novel is a thrilling masterpiece--from its opening pages to its stunning conclusion.",
                            Dimensions = "4.28 x 7.54 x 1.33 inches",
                            Edition = 2,
                            Genre = "Thriller",
                            Language = "English",
                            NumberOfPages = 608,
                            PhotoURL = "Dan-Brown_The-Da-Vinci-Code.jpg",
                            Price = 12.98,
                            PublisherID = 6,
                            PublisherName = "Macmillan Publishers",
                            Shipping = "Free",
                            SoldItems = 12,
                            Title = "The Da Vinci Code",
                            Weight = 0.48999999999999999,
                            YearOfIssue = new DateTime(2009, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            AuthorID = 10,
                            AuthorName = "Dan Brown",
                            BookType = "Paperback",
                            CategoryID = 7,
                            CategoryName = "Thrillers",
                            Copies = 100,
                            Country = "USA",
                            Description = "#1 WORLDWIDE BESTSELLER Harvard professor of symbology Robert Langdon awakens in an Italian hospital, disoriented and with no recollection of the past thirty-six hours, including the origin of the macabre object hidden in his belongings. With a relentless female assassin trailing them through Florence, he and his resourceful doctor, Sienna Brooks, are forced to flee. Embarking on a harrowing journey, they must unravel a series of codes, which are the work of a brilliant scientist whose obsession with the end of the world is matched only by his passion for one of the most influential masterpieces ever written, Dante Alighieri's \"The Inferno.\" Dan Brown has raised the bar yet again, combining classical Italian art, history, and literature with cutting-edge science in this sumptuously entertaining thriller.",
                            Dimensions = "4.28 x 7.54 x 1.33 inches",
                            Edition = 1,
                            Genre = "Thriller",
                            Language = "English",
                            NumberOfPages = 648,
                            PhotoURL = "Dan-Brown_Inferno.jpg",
                            Price = 5.9800000000000004,
                            PublisherID = 6,
                            PublisherName = "Macmillan Publishers",
                            Shipping = "Free",
                            SoldItems = 11,
                            Title = "Inferno",
                            Weight = 0.5,
                            YearOfIssue = new DateTime(2014, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            AuthorID = 1,
                            AuthorName = "Agatha Christie",
                            BookType = "Paperback",
                            CategoryID = 7,
                            CategoryName = "Thrillers",
                            Copies = 300,
                            Country = "UK",
                            Description = "No description is available.",
                            Dimensions = "5.82 x 8.52 x 0.94 inches",
                            Edition = 1,
                            Genre = "Thriller",
                            Language = "English",
                            NumberOfPages = 256,
                            PhotoURL = "AgathaCristie_13_Problems.jpg",
                            Price = 17.48,
                            PublisherID = 7,
                            PublisherName = "Simon & Schuster",
                            Shipping = "Free",
                            SoldItems = 11,
                            Title = "The Thirteen Problems",
                            Weight = 0.34999999999999998,
                            YearOfIssue = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            AuthorID = 1,
                            AuthorName = "Agatha Christie",
                            BookType = "Paperback",
                            CategoryID = 7,
                            CategoryName = "Thrillers",
                            Copies = 70,
                            Country = "UK",
                            Description = "When Alice Ascher is murdered in Andover, Hercule Poirot is already onto the clues. Alphabetically speaking, it's one down, 25 to go. This classic mystery is now repackaged in a digest-sized edition for young adults. Reissue.",
                            Dimensions = "5.82 x 8.52 x 0.94 inches",
                            Edition = 1,
                            Genre = "Thriller",
                            Language = "English",
                            NumberOfPages = 256,
                            PhotoURL = "AgathaCristie_TheABCMurders.jpg",
                            Price = 8.4800000000000004,
                            PublisherID = 7,
                            PublisherName = "Simon & Schuster",
                            Shipping = "Free",
                            SoldItems = 11,
                            Title = "The A.B.C. Murders",
                            Weight = 0.98999999999999999,
                            YearOfIssue = new DateTime(2006, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OnlineBookstore.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Thrillers"
                        },
                        new
                        {
                            Id = 8,
                            Name = "General"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Uncategorised"
                        });
                });

            modelBuilder.Entity("OnlineBookstore.Data.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("OnlineBookstore.Data.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Ireland",
                            Name = "William Morrow Paperbacks"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Name = "Scholastic"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Not known",
                            Name = "Penguin Random House"
                        },
                        new
                        {
                            Id = 4,
                            Country = "France",
                            Name = "Hachette Livre"
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            Name = "HarperCollins"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Germany",
                            Name = "Macmillan Publishers"
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            Name = "Simon & Schuster"
                        },
                        new
                        {
                            Id = 8,
                            Country = "USA",
                            Name = "McGraw-Hill Education"
                        },
                        new
                        {
                            Id = 9,
                            Country = "USA",
                            Name = "Houghton Mifflin Harcourt"
                        },
                        new
                        {
                            Id = 10,
                            Country = "USA",
                            Name = "Pearson Education"
                        });
                });

            modelBuilder.Entity("OnlineBookstore.Data.Entities.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookstore.Data.Entities.Author", b =>
                {
                    b.HasOne("OnlineBookstore.Data.Entities.Author", null)
                        .WithMany("Authors")
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("OnlineBookstore.Data.Entities.Book", b =>
                {
                    b.HasOne("OnlineBookstore.Data.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookstore.Data.Entities.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookstore.Data.Entities.Category", b =>
                {
                    b.HasOne("OnlineBookstore.Data.Entities.Category", null)
                        .WithMany("Categories")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("OnlineBookstore.Data.Entities.Photo", b =>
                {
                    b.HasOne("OnlineBookstore.Data.Entities.Book", null)
                        .WithMany("Photos")
                        .HasForeignKey("BookId");
                });

            modelBuilder.Entity("OnlineBookstore.Data.Entities.Publisher", b =>
                {
                    b.HasOne("OnlineBookstore.Data.Entities.Publisher", null)
                        .WithMany("Publishers")
                        .HasForeignKey("PublisherId");
                });
#pragma warning restore 612, 618
        }
    }
}
